### ISSUE TITLE
Breeding Planner GUI Bug

### ISSUE THREAD

**Issue by Mymsea** [cadon/ARKStatsExtractor#620]
The GUI for my breeding planner is messed up. Everything is way too close together.

![3](https://user-images.githubusercontent.com/36390523/36081404-5565a148-0f6c-11e8-84fd-7c79be7069b2.png)

[https://image.prntscr.com/image/UUBea-89Sv6xpXtE4yzHLA.png](url)

**Comment by Mymsea** [comment]
I've discovered that the issue is caused by High-DPI scaling. I fixed it by unchecking the option in the compatibility menu.
![2](https://user-images.githubusercontent.com/36390523/36099246-e32c81fa-0fcf-11e8-9822-43985580b558.png)

**Comment by cadon** [comment]
Hi, that's great news. I try to find a workaround for that issue for over a year. Thank you for sharing how to fix this!

**Comment by deedoubleu** [comment]
Alas, it's different in win7 and disabling display scaling doesn't fix the issue.

https://i.gyazo.com/0d3ebb2fc18617aa7772f31e70ac9a66.png

**Comment by Mymsea** [comment]
If you find the fix for windows 7, post it here.

**Comment by cadon** [comment]
The layout-method was changed, does it show correctly now?

**Comment by deedoubleu** [comment]
Win7 ASB user reporting in. Names are readable now. Thank you. Column names are slightly shifted.
https://i.gyazo.com/92a6a6986fa31901e1ae011287eb9ec1.png

Is it possible to use same method for pedigree tab? Atm it is very hard to understand.
https://i.gyazo.com/e7c32c00b1f829e8db678c1872cd8d72.png

**Comment by cadon** [comment]
Thanks for the feedback! The pedigree has a more complicated layout which isn't as easily put in a table, also the arrows are probably hard to set. I'll look into the column-headers in the breeding plan.

**Comment by Mymsea** [comment]
Why the fuck was I included in this email? Who are you people?

**Comment by kohonac** [comment]
@mymsea or maybe because you started this github issue on 2/11/2018. maybe try and read what you get and you may figure out why you are getting emails

**Comment by Mymsea** [comment]
I've never heard of github before this. Plz stop emailing me.

**Comment by kohonac** [comment]
if you didnt use your email to sigh up for GitHUb then i suggest that you change your password as someone used your email to sign up and account and post this ticket
![image](https://user-images.githubusercontent.com/3374605/38169776-415444e8-3528-11e8-9e1f-886f08ec05cd.png)

**Comment by cadon** [comment]
@Mymsea if you didn't set up this account which uses your email, I suggest you write to the support of github here https://github.com/contact. Like kohonac wrote, someone took your email-adress to create the account https://github.com/Mymsea. Changing your password of this email-account is advised as well.

**Comment by harry323** [comment]
I'm still having an issue similar to this one:

![image](https://user-images.githubusercontent.com/46381622/71912332-ee0e4c00-313a-11ea-8610-2fea58e633be.png)

The female side aligns just fine but the male side gets a little compacted and the columns are slightly  misaligned. It just makes things a little difficult to check at a glance.

**Comment by cadon** [comment]
@harry323 the layout of that was partly fixed some time ago, but the breeding scores apparently still are affected by different DPI settings. I'll see what I can do in this case, it's a bit more complicated.

**Comment by harry323** [comment]
@cadon Thanks for that. If there's a setting change that I can make on my end then I'll be happy to set it properly so that you don't have to do any tinkering.

**Comment by harry323** [comment]
@cadon I figured out the issue. In my Windows 10 Settings I had the Scale and layout setting changed to 225% from the recommended settings of 100%. Incidentally I realized this while doing something entirely different. Once I changed the scaling percentage to 100% ARK Smart Breeding displays everything correctly including the Taming and Breeding Plan tabs.

**Comment by cadon** [comment]
closing as being duplicate of #151.
